// Mock data for the helpdesk

const CATEGORIES = [
  {
    id: 'primeiros-passos',
    name: 'Primeiros Passos',
    icon: 'rocket',
    desc: 'Onboarding e configuração inicial.',
    count: 12,
    sub: [
      { id: 'criar-conta', name: 'Criar conta', count: 3 },
      { id: 'painel', name: 'Tour do painel', count: 4 },
      { id: 'primeira-hosp', name: 'Primeira hospedagem', count: 5 },
    ],
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    icon: 'edit',
    desc: 'Instalação, plugins, performance e migração.',
    count: 34,
    sub: [
      { id: 'instalacao', name: 'Instalação', count: 6 },
      { id: 'migracao', name: 'Migração', count: 8 },
      { id: 'plugins', name: 'Plugins essenciais', count: 7 },
      { id: 'performance', name: 'Performance', count: 9 },
      { id: 'erros-wp', name: 'Erros comuns', count: 4 },
    ],
  },
  {
    id: 'dominios',
    name: 'Domínios e DNS',
    icon: 'globe',
    desc: 'Registro, transferência e configuração.',
    count: 21,
    sub: [
      { id: 'registro', name: 'Registro', count: 4 },
      { id: 'dns-zona', name: 'Zona DNS', count: 9 },
      { id: 'transferencia', name: 'Transferência', count: 5 },
      { id: 'ssl', name: 'SSL', count: 3 },
    ],
  },
  {
    id: 'email',
    name: 'E-mail',
    icon: 'mail',
    desc: 'Contas profissionais e configuração SMTP/IMAP.',
    count: 18,
    sub: [
      { id: 'criar-email', name: 'Criar conta', count: 4 },
      { id: 'webmail', name: 'Webmail', count: 3 },
      { id: 'smtp-imap', name: 'SMTP/IMAP', count: 6 },
      { id: 'antispam', name: 'Antispam e DMARC', count: 5 },
    ],
  },
  {
    id: 'vps',
    name: 'VPS e Projetos',
    icon: 'server',
    desc: 'Servidores dedicados e projetos de hospedagem.',
    count: 27,
    sub: [
      { id: 'criar-vps', name: 'Criar VPS', count: 5 },
      { id: 'ssh', name: 'Acesso SSH', count: 6 },
      { id: 'snapshots', name: 'Snapshots', count: 4 },
      { id: 'firewall', name: 'Firewall', count: 7 },
      { id: 'monitor', name: 'Monitoramento', count: 5 },
    ],
  },
  {
    id: 'seguranca',
    name: 'Segurança e Backup',
    icon: 'shield',
    desc: 'Proteção do site e recuperação de dados.',
    count: 19,
    sub: [
      { id: 'backup', name: 'Backups', count: 6 },
      { id: 'restore', name: 'Restauração', count: 4 },
      { id: '2fa', name: '2FA', count: 3 },
      { id: 'malware', name: 'Malware', count: 6 },
    ],
  },
  {
    id: 'faturamento',
    name: 'Faturamento',
    icon: 'credit-card',
    desc: 'Planos, pagamentos, NF e cancelamentos.',
    count: 15,
    sub: [
      { id: 'pagamento', name: 'Métodos de pagamento', count: 4 },
      { id: 'nf', name: 'Notas fiscais', count: 5 },
      { id: 'upgrade', name: 'Upgrade/Downgrade', count: 3 },
      { id: 'cancel', name: 'Cancelamento', count: 3 },
    ],
  },
  {
    id: 'afiliados',
    name: 'Afiliados',
    icon: 'users',
    desc: 'Programa de afiliados e comissões.',
    count: 8,
    sub: [
      { id: 'inscricao', name: 'Inscrição', count: 2 },
      { id: 'comissao', name: 'Comissões', count: 3 },
      { id: 'saque', name: 'Saques', count: 3 },
    ],
  },
];

const TAG_STYLES = {
  tutorial: { bg: 'var(--blue-bg)', fg: '#1d4ed8', label: 'Tutorial' },
  troubleshooting: { bg: 'var(--rose-bg)', fg: '#9f1239', label: 'Troubleshooting' },
  faq: { bg: 'var(--teal-bg)', fg: '#0f766e', label: 'FAQ' },
  config: { bg: 'var(--amber-bg)', fg: '#92400e', label: 'Configuração' },
  policy: { bg: 'var(--purple-100)', fg: 'var(--purple-700)', label: 'Política' },
};

const ARTICLES = [
  {
    id: 'a01',
    title: 'Erro 500 após instalação de plugin — diagnóstico e rollback',
    cat: 'wordpress', sub: 'erros-wp',
    tag: 'troubleshooting',
    views: 4821, updated: '08 mai 2026',
    estimate: '6 min',
    excerpt: 'Procedimento padrão para identificar plugin conflitante, ativar log de debug e fazer rollback via SSH ou Gerenciador.',
    hot: true,
    pinned: true,
  },
  {
    id: 'a02',
    title: 'Como migrar site WordPress de outra hospedagem',
    cat: 'wordpress', sub: 'migracao',
    tag: 'tutorial',
    views: 3940, updated: '02 mai 2026',
    estimate: '12 min',
    excerpt: 'Fluxo completo de migração assistida + uso da ferramenta de import automático do painel.',
    hot: true,
  },
  {
    id: 'a03',
    title: 'Configurar SPF, DKIM e DMARC para evitar spam',
    cat: 'email', sub: 'antispam',
    tag: 'config',
    views: 3210, updated: '28 abr 2026',
    estimate: '8 min',
    excerpt: 'Registros recomendados e como validar via mxtoolbox e console interno.',
    hot: true,
  },
  {
    id: 'a04',
    title: 'Apontar domínio externo (Registro.br) para a TurboCloud',
    cat: 'dominios', sub: 'registro',
    tag: 'tutorial',
    views: 2987, updated: '06 mai 2026',
    estimate: '5 min',
    excerpt: 'Nameservers e prazo de propagação. Inclui screenshots do painel Registro.br.',
    hot: true,
  },
  {
    id: 'a05',
    title: 'SSL não renova automaticamente — checklist de causas',
    cat: 'dominios', sub: 'ssl',
    tag: 'troubleshooting',
    views: 2104, updated: '10 mai 2026',
    estimate: '4 min',
    excerpt: 'Verificações em ordem: DNS, .well-known, CAA, rate limit Let\u2019s Encrypt.',
    pinned: true,
  },
  {
    id: 'a06',
    title: 'Restaurar backup parcial de um site WordPress',
    cat: 'seguranca', sub: 'restore',
    tag: 'tutorial',
    views: 1820, updated: '11 mai 2026',
    estimate: '7 min',
    excerpt: 'Restaurar apenas arquivos, apenas banco, ou um diretório específico via painel.',
  },
  {
    id: 'a07',
    title: 'Política de reembolso e cancelamento de planos',
    cat: 'faturamento', sub: 'cancel',
    tag: 'policy',
    views: 1655, updated: '14 abr 2026',
    estimate: '3 min',
    excerpt: 'Janela de 7 dias, casos elegíveis e procedimento interno para devolução.',
  },
  {
    id: 'a08',
    title: 'Liberar IP no firewall do VPS (UFW)',
    cat: 'vps', sub: 'firewall',
    tag: 'config',
    views: 1432, updated: '09 mai 2026',
    estimate: '4 min',
    excerpt: 'Comandos ufw allow, status numbered e regras persistentes após reboot.',
  },
  {
    id: 'a09',
    title: 'Cliente não recebe e-mails — protocolo de investigação',
    cat: 'email', sub: 'antispam',
    tag: 'troubleshooting',
    views: 1289, updated: '07 mai 2026',
    estimate: '6 min',
    excerpt: 'MX, blacklist, espaço em caixa, regra de filtro. Checklist do atendimento.',
  },
  {
    id: 'a10',
    title: 'Como ler o gráfico de uso de CPU/RAM no painel',
    cat: 'vps', sub: 'monitor',
    tag: 'faq',
    views: 1108, updated: '01 mai 2026',
    estimate: '3 min',
    excerpt: 'Interpretação dos picos, médias móveis e quando recomendar upgrade.',
  },
  {
    id: 'a11',
    title: 'Recuperar acesso ao wp-admin (perda de senha admin)',
    cat: 'wordpress', sub: 'erros-wp',
    tag: 'troubleshooting',
    views: 1054, updated: '05 mai 2026',
    estimate: '5 min',
    excerpt: 'Via WP-CLI, via phpMyAdmin e via reset por e-mail forçado.',
  },
  {
    id: 'a12',
    title: 'Diferença entre VPS Compartilhado e VPS Dedicado',
    cat: 'vps', sub: 'criar-vps',
    tag: 'faq',
    views: 980, updated: '15 abr 2026',
    estimate: '2 min',
    excerpt: 'Tabela comparativa, casos de uso e recomendação por porte de cliente.',
  },
  {
    id: 'a13',
    title: 'Habilitar 2FA para o painel TurboCloud',
    cat: 'seguranca', sub: '2fa',
    tag: 'tutorial',
    views: 870, updated: '12 mai 2026',
    estimate: '3 min',
    excerpt: 'Apps suportados, códigos de recuperação e revogação.',
  },
  {
    id: 'a14',
    title: 'Emitir nota fiscal de competência anterior',
    cat: 'faturamento', sub: 'nf',
    tag: 'faq',
    views: 760, updated: '20 abr 2026',
    estimate: '2 min',
    excerpt: 'Limite de 60 dias, contato com financeiro e procedimento manual.',
  },
  {
    id: 'a15',
    title: 'Acesso SSH com chave pública (boas práticas)',
    cat: 'vps', sub: 'ssh',
    tag: 'tutorial',
    views: 690, updated: '03 mai 2026',
    estimate: '5 min',
    excerpt: 'Geração de chave ed25519, deploy via painel e desativação de senha.',
  },
  {
    id: 'a16',
    title: 'Snapshots automáticos: política e retenção',
    cat: 'vps', sub: 'snapshots',
    tag: 'policy',
    views: 540, updated: '18 abr 2026',
    estimate: '3 min',
    excerpt: 'Frequência, janela de retenção por plano e custo de snapshots manuais.',
  },
];

const ANNOUNCEMENTS = [
  { id: 'an1', type: 'incident', title: 'Manutenção programada — cluster SP-02', when: '15 mai · 02h-04h', status: 'agendado' },
  { id: 'an2', type: 'release', title: 'Novo fluxo de emissão de NF retroativa', when: '08 mai', status: 'release' },
  { id: 'an3', type: 'policy', title: 'Atualização da política de reembolso (7 → 14 dias)', when: '02 mai', status: 'política' },
];

const RECENT = ['a01', 'a05', 'a09', 'a13'];

window.CATEGORIES = CATEGORIES;
window.TAG_STYLES = TAG_STYLES;
window.ARTICLES = ARTICLES;
window.ANNOUNCEMENTS = ANNOUNCEMENTS;
window.RECENT = RECENT;
